[GLOBAL]
pants_version = "2.9.0"

backend_packages = [
  "pants.backend.experimental.docker",
  "pants.backend.experimental.docker.lint.hadolint"
]

[docker]
env_vars = [
  "DOCKER_TLS_VERIFY",
  "DOCKER_CERT_PATH",
  "DOCKER_HOST"
]
